---
collections:
  - name: community.crypto
    version: 2.15.1
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 9.5.12
  - name: community.sap_install
    version: 1.7.1
