psmiscVersionMatrix:
  -
    os: '12.5'
    version: '22.21-6.25.1'
  -
    os: '15'
    version: '23.0-6.7.1'
  -
    os: '15.1'
    version: '23.0-6.7.1'
  -
    os: '15.2'
    version: '23.0-6.16.1'
  -
    os: '15.3'
    version: '23.0-6.19.1'
  -
    os: '15.4'
    version: '23.0-150000.6.22.1'