---
galaxy_info:
  namespace: community
  author: IBM Lab for SAP Solutions, Red Hat for SAP Community of Practice, Jason Masipiquena, Sherard Guico, Markus Moster
  description: Installation of SAP HANA System Replication on Linux OS (RHEL, SLES)
  company: Red Hat, Inc.
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions: ["7", "8", "9"]
    - name: SLES
      versions: ["15SP3"]
  galaxy_tags:
    [
      "sap",
      "hana",
      "ha",
      "dr",
      "ha/dr",
      "linuxpacemaker",
      "rhel",
      "redhat",
      "sles",
      "suse",
    ]
dependencies: []
