---

- name: SAP HANA Post Install - Set log_mode to overwrite
  ansible.builtin.shell: |
      LD_LIBRARY_PATH=/usr/sap/{{ sap_hana_install_sid }}/HDB{{ sap_hana_install_number }}/exe \
      /usr/sap/{{ sap_hana_install_sid }}/SYS/exe/hdb/hdbsql \
      -n '{{ ansible_hostname }}' \
      -i '{{ sap_hana_install_number }}' \
      -d SYSTEMDB \
      -u SYSTEM \
      -p '{{ sap_hana_install_db_system_password|d(sap_hana_install_master_password) }}' \
      -m <<EOF
      ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'SYSTEM') SET ('persistence', 'log_mode') = 'overwrite' WITH RECONFIGURE;
      ALTER SYSTEM ALTER CONFIGURATION('global.ini','HOST','{{ ansible_hostname }}') SET ('persistence','log_mode') = 'overwrite' WITH RECONFIGURE;
      ALTER SYSTEM ALTER CONFIGURATION('global.ini','DATABASE','{{ sap_hana_install_sid }}') SET ('persistence','log_mode') = 'overwrite' WITH RECONFIGURE;
      EOF
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_install_sid | lower }}adm"
  when:
    - not ansible_check_mode
    - sap_hana_set_log_mode_overwrite
  changed_when: false
  register: __sap_hana_install_hdbsql_logmode
  tags: sap_hana_install_set_log_mode

- name: SAP HANA Post Install - Display the output of hdbsql
  ansible.builtin.debug:
    var: __sap_hana_install_hdbsql_logmode.stdout_lines
  tags: sap_hana_install_set_log_mode
  when: sap_hana_set_log_mode_overwrite
