---
galaxy_info:
  namespace: community
  author: Red Hat for SAP Community of Practice, IBM Lab for SAP Solutions, Markus Koch, Thomas Bludau, Bernd Finger, Than Ngo, Rainer Leber
  description: Installation of SAP HANA on Linux OS (RHEL, SLES)
  company: Red Hat, Inc.
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions: [7, 8, 9]
  galaxy_tags: ['sap', 'hana', 'rhel', 'redhat', 'sles', 'suse']
dependencies: []
