---

################
# Azure Specific Pre-Tasks
################

# Create json format of IMDS
- name: SAP Storage Preparation - Create json format of IMDS - {{ qe_sap_storage_cloud_type | upper }}
  ansible.builtin.uri:
    url: "{{ qe_sap_storage_az_imds_url }}"
    method: GET
    headers:
      Metadata: true
  register: qe_sap_storage_az_imds_reg
  changed_when: false

# If this fails, that means this VM is not Azure?

- name: Store imds json
  ansible.builtin.set_fact:
    qe_sap_storage_az_imds_json: "{{ qe_sap_storage_az_imds_reg.json }}"

# Pull VMSize
- name: SAP Storage Preparation - Pull VMSize - {{ qe_sap_storage_cloud_type | upper }}
  ansible.builtin.uri:
    url: "{{ qe_sap_storage_az_vmsize_url }}"
    method: GET
    headers:
      Metadata: true
    return_content: true
  register: qe_sap_storage_az_vmsize_reg
  changed_when: false

- name: VM size output
  ansible.builtin.debug:
    msg:
      - "{{ qe_sap_storage_az_vmsize_reg.content }}"

- name: Calculate qe_sap_storage_az_vmsize
  ansible.builtin.set_fact:
    qe_sap_storage_az_vmsize: "{{ qe_sap_storage_az_vmsize_reg.content }}"

# Include vars depending on VM Size
- name: SAP Storage Preparation - Load Variables for {{ qe_sap_storage_az_vmsize }}
  ansible.builtin.include_vars: "{{ qe_sap_storage_cloud_type }}_tasks/vmsizes/{{ qe_sap_storage_az_vmsize }}.yml"
