---

################
# Cloud Specific Pre-Tasks - call cloud specific pre tasks thru {{ qe_sap_storage_cloud_type }}_main.yml
################

- name: SAP Storage Preparation - {{ qe_sap_storage_cloud_type }}
  ansible.builtin.include_tasks: "{{ qe_sap_storage_cloud_type }}_main.yml"

################
# Main Run - call cloud specific tasks thru {{ qe_sap_storage_cloud_type }}_tasks/prep_storage.yml
################

- name: SAP Storage Preparation - Volume Groups and Logical Volumes - {{ qe_sap_storage_action | capitalize }}
  ansible.builtin.include_tasks: "{{ qe_sap_storage_cloud_type }}_tasks/{{ qe_sap_storage_action }}_storage.yml"
  loop: "{{ lookup('dict', sap_storage_dict, wantlist=True) }}"
