---
- name: "SAP HSR - Delete linux entry in /etc/hosts"
  shell: sed -i '/linux/d' /etc/hosts
  register: clean_etchosts

- name: "SAP HSR - Add Cluster Nodes to /etc/hosts"
  lineinfile:
    path: /etc/hosts
    create: true
    state: present
    backup: true
    line: "{{ item.node_ip }}\t{{ item.node_name }}.{{ sap_ha_install_hana_hsr_fqdn }}\t{{ item.node_name }}"
    regexp: (?i)^\s*{{ item.node_ip }}\s+{{ item.node_name }}
  loop: "{{ sap_ha_install_hana_hsr_cluster_nodes }}"
  loop_control:
    label: "{{ item.node_ip }} {{ item.node_name }}.{{ sap_ha_install_hana_hsr_fqdn }} {{ item.node_name }}"
  when: clean_etchosts == 0

- name: "SAP HSR - Check /etc/hosts for conflicting entries"
  shell: |
    awk '(/{{ item.node_name }}/ && !/^{{ item.node_ip }}/) || (/^{{ item.node_ip }}/ && !/{{ item.node_name }}/)' /etc/hosts
  register: etchosts_conflict
  changed_when: false
  failed_when: etchosts_conflict.stdout != ''
  loop: "{{ sap_ha_install_hana_hsr_cluster_nodes }}"
  loop_control:
    label: "Check if {{ item.node_ip }} exists for hosts other than {{ item.node_name }}"
