---

- name: SAP HANA hdblcm prepare - Check if checksum file exists
  ansible.builtin.stat:
    path: "{{ __sap_hana_install_passed_file_dict.checksum_file }}"
  register: __sap_hana_install_register_stat_checksum_file

- name: SAP HANA hdblcm prepare - Fail if the checksum file is missing
  ansible.builtin.fail:
    msg: "FAIL: Missing checksum file '{{ __sap_hana_install_passed_file_dict.checksum_file }}'!"
  when: not __sap_hana_install_register_stat_checksum_file.stat.exists

- name: Continue if checksum file exists
  block:

# We are using awk to search for the file name in the checksum file. If there is no entry for the file, instead of
# displaying the checksum for the file, we display the string 'Missing entry' on stdout.
# Reason for noqa: A double brace might also occur in an awk command sequence.
    - name: SAP HANA hdblcm prepare - Get expected checksum from file # noqa var-spacing
      ansible.builtin.command: "awk 'BEGIN{a=0}/{{ __sap_hana_install_passed_file_dict.file }}/{a++; print $1}END{if (a==0){print \"Missing entry\"}}' {{ __sap_hana_install_passed_file_dict.checksum_file }}"
      check_mode: no
      register: __sap_hana_install_register_checksum_from_file
      changed_when: no

    - name: SAP HANA hdblcm prepare - Fail if an entry for file '{{ __sap_hana_install_passed_file_dict.file }}' is missing in '{{ __sap_hana_install_passed_file_dict.checksum_file }}'
      ansible.builtin.fail:
        msg: "FAIL: Missing entry for file '{{ __sap_hana_install_passed_file_dict.file }}' in '{{ __sap_hana_install_passed_file_dict.checksum_file }}'!"
      when: __sap_hana_install_register_checksum_from_file.stdout == 'Missing entry'

    - name: SAP HANA hdblcm prepare - Calculate checksum of '{{ __sap_hana_install_passed_file_dict.file }}'
      ansible.builtin.stat:
        path: "{{ __sap_hana_install_passed_file_dict.dir }}/{{ __sap_hana_install_passed_file_dict.file }}"
        checksum_algorithm: "{{ sap_hana_install_checksum_algorithm }}"
      register: __sap_hana_install_register_stat_file
      when: __sap_hana_install_register_checksum_from_file.stdout != 'Missing entry'

    - name: SAP HANA hdblcm prepare - Assert that the checksum of the SAR file is correct
      ansible.builtin.assert:
        that: __sap_hana_install_register_stat_file.stat.checksum ==
              __sap_hana_install_register_checksum_from_file.stdout.split(' ').0
        fail_msg: "FAIL: The checksum of file '{{ __sap_hana_install_passed_file_dict.dir }}/{{ __sap_hana_install_passed_file_dict.file }}'
           does not match the checksum stored in file '{{ __sap_hana_install_passed_file_dict.checksum_file }}'!"
        success_msg: "PASS: The checksum of file '{{ __sap_hana_install_passed_file_dict.dir }}/{{ __sap_hana_install_passed_file_dict.file }}'
           matches the checksum stored in file '{{ __sap_hana_install_passed_file_dict.checksum_file }}'."
      when: __sap_hana_install_register_checksum_from_file.stdout != 'Missing entry'

  when: __sap_hana_install_register_stat_checksum_file.stat.exists
