---
- name: IBSM
  hosts: all
  remote_user: cloudadmin
  become: true
  become_user: root

  tasks:

    - name: Assert that required variables are defined
      ansible.builtin.assert:
        that: "{{ item }} is defined"
        fail_msg: >-
          The required variable '{{ item }}' is not defined. This variable must be
          defined when using this playbook.
        success_msg: >-
          The variable '{{ item }}' is defined.
      loop:
        - 'ibsm_ip'
        - 'download_hostname'

    - name: Add mirror to hosts
      ansible.builtin.lineinfile:
        path: "/etc/hosts"
        line: "{{ ibsm_ip }}  {{ download_hostname }}"
        state: present

    - name: Zypper add repo
      community.general.zypper_repository:
        repo: "{{ item }}"
        name: "TEST_{{ repo_id }}"
        disable_gpg_check: true
        autorefresh: true
        priority: "{{ priority | default(omit) }}"
      loop: "{{ repos.split(',') }}"
      loop_control:
        index_var: repo_id
      when: repos | length > 0
      environment:
        ZYPP_LOCK_TIMEOUT: '120'

    - name: Refresh all repos
      community.general.zypper_repository:
        repo: '*'
        runrefresh: true
