---
- hosts: all
  remote_user: cloudadmin
  become: true
  become_user: root

  vars:
    use_suseconnect: false  # Set to false unless specified

  tasks:

    # Pre flight checks
    # Do we have repos?  If not, we need to register
    - name: Check for registration
      ansible.builtin.command: SUSEConnect -s
      register: repos
      failed_when: false
      changed_when: false

    # Check if there are instances of `Not Registered` in it
    - name: Check for 'Not Registered'
      set_fact:
        not_registered_found: "{{ 'Not Registered' in repos.stdout }}"
      ignore_errors: true

    # Is registercloudguest available?
    - name: Check for registercloudguest
      ansible.builtin.command: which registercloudguest
      register: rcg
      failed_when: false
      changed_when: false
      when:
        - not_registered_found

    # Execute Section
    - name: registercloudguest pre-run cleaning
      ansible.builtin.command: registercloudguest --clean
      when:
        - not_registered_found
        - rcg.rc == 0
        - not use_suseconnect | bool

    - name: registercloudguest registration
      ansible.builtin.command: registercloudguest --force-new -r "{{ reg_code }}" -e "{{ email_address }}"
      register: result
      until: result is succeeded
      retries: 10
      delay: 60
      failed_when: result.rc != 0 or result.stderr != ""
      when:
        - not_registered_found
        - rcg.rc == 0
        - not use_suseconnect | bool

    # If registercloudguest is not present fall back on SUSEConnect
    - name: SUSEConnect registration
      ansible.builtin.command: SUSEConnect -r "{{ reg_code }}" -e "{{ email_address }}"
      register: result
      until: result is succeeded
      retries: 10
      delay: 60
      when:
        - not_registered_found
        - "(rcg.rc != 0) or (use_suseconnect | bool)"

    # There are additional repos to add.  These are handled differently for SLES 15 and SLES12
    - name: Add SLES 12 Advanced Systems Modules
      ansible.builtin.command: SUSEConnect -p sle-module-adv-systems-management/12/{{ ansible_facts['architecture'] }} -r "{{ reg_code }}"
      register: result
      until: result is succeeded
      retries: 10
      delay: 60
      when:
        - ansible_facts['distribution_major_version'] == "12"
        - not_registered_found
        - "(rcg.rc != 0) or (use_suseconnect | bool)"

    - name: Add SLES 12 public cloud module
      ansible.builtin.command: SUSEConnect -p sle-module-public-cloud/12/{{ ansible_facts['architecture'] }}
      register: result
      until: result is succeeded
      retries: 10
      delay: 60
      when:
        - ansible_facts['distribution_major_version'] == "12"
        - not_registered_found
        - "(rcg.rc != 0) or (use_suseconnect | bool)"

    - name: Add SLES 15 public cloud module
      ansible.builtin.command: SUSEConnect -p sle-module-public-cloud/{{ ansible_facts['distribution_version'] }}/{{ ansible_facts['architecture'] }}
      register: result
      until: result is succeeded
      retries: 10
      delay: 60
      when:
        - ansible_facts['distribution_major_version'] == "15"
        - not_registered_found
        - "(rcg.rc != 0) or (use_suseconnect | bool)"

    # Latest version of cloud-regionsrv-client is needed in PAYG, and image
    # needs to be registered in order for zypper up to work.
    # see https://www.suse.com/c/long-term-service-pack-support-for-payg-instances-simplified/
    - name: Ensure cloud-regionsrv-client is on latest version.
      community.general.zypper:
        name: cloud-regionsrv-client
        state: latest
      when:
        - not not_registered_found
        - sles_modules is defined and sles_modules | length > 0

    - name: Add additional authenticated modules
      ansible.builtin.command: SUSEConnect -p {{ item.key }} -r {{ item.value }}
      register: result
      until: result is succeeded
      retries: 10
      delay: 60
      when:
        - not_registered_found
        - sles_modules is defined and sles_modules | length > 0
      loop: "{{ sles_modules }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Check if repos are added after registration
      ansible.builtin.command: zypper lr -u
      register: repos_after
      failed_when: repos_after.rc != 0
      when:
        - not_registered_found
