---
- name: Register
  hosts: all
  remote_user: cloudadmin
  become: true
  become_user: root
  environment:
    ZYPP_LOCK_TIMEOUT: '120'

  vars:
    use_suseconnect: false  # Set to false unless specified

  tasks:

    # Pre flight checks
    - name: Check for instance-flavor-check presence
      ansible.builtin.command: which instance-flavor-check
      register: ifc_bin
      changed_when: false
      failed_when: false

    - name: Check for SUSEConnect binary presence
      ansible.builtin.command: which SUSEConnect
      changed_when: false

    - name: Check for image type with instance-flavor-check
      ansible.builtin.command: instance-flavor-check
      register: flavor
      failed_when: flavor.rc not in [10, 11, 12]
      changed_when: false
      when: ifc_bin.rc == 0

    - name: Set registration flag based on instance-flavor-check
      ansible.builtin.set_fact:
        to_be_registered: "{{ 'BYOS' in flavor.stdout }}"
      when: ifc_bin.rc == 0

    # If instance-flavor-check is not available
    # try to figure it out if image is PAYG or BYOS looking
    # for not registered repos
    - name: Check for registration
      ansible.builtin.command: SUSEConnect -s
      register: repos
      until: repos.rc == 0
      retries: 5
      delay: 120
      failed_when: repos.rc != 0
      changed_when: false
      when: ifc_bin.rc != 0

    # Check if there are instances of `Not Registered` in it
    - name: Check for 'Not Registered'
      ansible.builtin.set_fact:
        to_be_registered: "{{ 'Not Registered' in repos.stdout }}"
      when: ifc_bin.rc != 0

    # Is registercloudguest available?
    # only run it if:
    #  - there's at least one 'Not Registered' module
    - name: Check for registercloudguest
      ansible.builtin.command: which registercloudguest
      register: is_registercloudguest_bin
      failed_when: false
      changed_when: false

    # Next four tasks are about bug bsc 1217583. This bug is already fixed
    # in cloud-regionsrv-client 10.1.7, but SLES 15SP2 does not have it in
    # the image, only get it after an update. But, at least for BYOS images,
    # update is not possible with registercloudguest, due to the bug itself.
    # Workaround is to force registration with SUSEConnect
    - name: Gather the package facts to check cloud-regionsrv-client in 15sp2
      ansible.builtin.package_facts:
        manager: auto
      when:
        - ansible_facts['distribution_version'] == '15.2'
        - not use_suseconnect | bool

    - name: Softfail for old cloud-regionsrv-client in 15sp2
      ansible.builtin.debug:
        msg:
          - "[OSADO][softfail] bsc#1217583 IPv6 handling during registration"
          - "use_suseconnect: {{ use_suseconnect }}"
      when:
        - ansible_facts['distribution_version'] == '15.2'
        - ansible_facts.packages['cloud-regionsrv-client'][0].version is version('10.1.7', '<')
        - not use_suseconnect | bool

    - name: Force SUSEConnect usage in case of old cloud-regionsrv-client avoiding 1217583
      ansible.builtin.set_fact:
        use_suseconnect: true
      when:
        - ansible_facts['distribution_version'] == '15.2'
        - ansible_facts.packages['cloud-regionsrv-client'][0].version is version('10.1.7', '<')
        - not use_suseconnect | bool

    - name: Validate reg code
      ansible.builtin.assert:
        that:
          - reg_code | length > 0
        fail_msg: "'reg_code' must not be empty"
        success_msg: "'reg_code' is OK"
      changed_when: false
      when:
        - to_be_registered
        - is_registercloudguest_bin.rc == 0
        - not use_suseconnect | bool

    # Start by pre-cleaning all. Only run it if:
    #  - the registercloudguest binary is available
    #  - there's at least one 'Not Registered' module
    #  - the user does not force SUSEConnect usage with 'use_suseconnect'
    - name: Pre-run cleaning registercloudguest
      ansible.builtin.command: registercloudguest --clean
      register: cleanout
      changed_when: cleanout.rc == 0
      when:
        - to_be_registered
        - is_registercloudguest_bin.rc == 0
        - not use_suseconnect | bool

    - name: Run registercloudguest registration
      ansible.builtin.command: registercloudguest --force-new -r "{{ reg_code }}" -e "{{ email_address }}"
      register: result
      until: result is succeeded
      retries: 10
      delay: 60
      failed_when: result.rc != 0 or result.stderr != ""
      changed_when: result.rc == 0
      when:
        - to_be_registered
        - is_registercloudguest_bin.rc == 0
        - not use_suseconnect | bool

    # Fall back on SUSEConnect if:
    #   - registercloudguest is not present
    # or
    #   - the user explicitly require using SUSEConnect
    - name: SUSEConnect registration
      ansible.builtin.command: SUSEConnect -r "{{ reg_code }}" -e "{{ email_address }}"
      register: result
      changed_when: result.rc == 0
      until: result is succeeded
      retries: 10
      delay: 60
      when:
        - to_be_registered
        - "(is_registercloudguest_bin.rc != 0) or (use_suseconnect | bool)"

    # There are additional repos to add.
    # These are handled differently for SLES 15 and SLES12
    - name: Add SLES 12 Advanced Systems Modules
      ansible.builtin.command: SUSEConnect -p sle-module-adv-systems-management/12/{{ ansible_facts['architecture'] }} -r "{{ reg_code }}"
      register: result
      changed_when: result.rc == 0
      until: result is succeeded
      retries: 10
      delay: 60
      when:
        - ansible_facts['distribution_major_version'] == "12"
        - to_be_registered
        - "(is_registercloudguest_bin.rc != 0) or (use_suseconnect | bool)"

    - name: Add SLES 12 public cloud module
      ansible.builtin.command: SUSEConnect -p sle-module-public-cloud/12/{{ ansible_facts['architecture'] }}
      register: result
      changed_when: result.rc == 0
      until: result is succeeded
      retries: 10
      delay: 60
      when:
        - ansible_facts['distribution_major_version'] == "12"
        - to_be_registered
        - "(is_registercloudguest_bin.rc != 0) or (use_suseconnect | bool)"

    - name: Add SLES 15 public cloud module
      ansible.builtin.command: SUSEConnect -p sle-module-public-cloud/{{ ansible_facts['distribution_version'] }}/{{ ansible_facts['architecture'] }}
      register: result
      changed_when: result.rc == 0
      until: result is succeeded
      retries: 10
      delay: 60
      when:
        - ansible_facts['distribution_major_version'] == "15"
        - to_be_registered
        - "(is_registercloudguest_bin.rc != 0) or (use_suseconnect | bool)"

    # Latest version of cloud-regionsrv-client is needed in PAYG, and image
    # needs to be registered in order for zypper up to work.
    # see https://www.suse.com/c/long-term-service-pack-support-for-payg-instances-simplified/
    - name: Ensure cloud-regionsrv-client is on latest version.
      community.general.zypper:
        name: cloud-regionsrv-client
        state: latest
      when:
        - sles_modules is defined and sles_modules | length > 0

    - name: Add additional authenticated modules [SUSEConnnect]
      ansible.builtin.command: SUSEConnect -p {{ item.key }} -r {{ item.value }}
      register: result
      changed_when: result.rc == 0
      until: result is succeeded
      retries: 10
      delay: 60
      when:
        - sles_modules is defined and sles_modules | length > 0
        - "(is_registercloudguest_bin.rc != 0) or (use_suseconnect | bool)"
      loop: "{{ sles_modules }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Add additional authenticated modules [registercloudguest]
      ansible.builtin.command: registercloudguest -r {{ item.value }}
      register: result
      changed_when: result.rc == 0
      until: result is succeeded
      retries: 10
      delay: 60
      when:
        - sles_modules is defined and sles_modules | length > 0
        - is_registercloudguest_bin.rc == 0
        - not use_suseconnect | bool
      loop: "{{ sles_modules }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Check if repos are added after registration
      ansible.builtin.command: zypper lr -u
      register: repos_after
      failed_when: repos_after.rc != 0
      changed_when: false
