---

- name: SAP HANA Post Install - Create and Store Connection Info in hdbuserstore
  ansible.builtin.shell: |
      /usr/sap/{{ sap_hana_install_sid }}/SYS/exe/hdb/hdbuserstore \
      SET {{ sap_hana_install_hdbuserstore_key }} \
      {{ ansible_hostname }}:3{{ sap_hana_install_number }}13 \
      SYSTEM '{{ sap_hana_install_db_system_password|d(sap_hana_install_master_password) }}'
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_install_sid | lower }}adm"
  when: not ansible_check_mode
  changed_when: no
  register: __sap_hana_install_store_connection_information
  tags: sap_hana_install_store_connection_information

- name: SAP HANA Post Install - Display the output of hdbuserstore
  ansible.builtin.debug:
    var: __sap_hana_install_store_connection_information.stdout_lines
  tags: sap_hana_install_store_connection_information
