---

- name: SAP HANA Post Install - Recreate the tenant database
  ansible.builtin.shell: |
      LD_LIBRARY_PATH=/usr/sap/{{ sap_hana_install_sid }}/HDB{{ sap_hana_install_number }}/exe \
      /usr/sap/{{ sap_hana_install_sid }}/SYS/exe/hdb/hdbsql \
      -n '{{ ansible_hostname }}' \
      -i '{{ sap_hana_install_number }}' \
      -d SYSTEMDB \
      -u SYSTEM \
      -p '{{ sap_hana_install_db_system_password|d(sap_hana_install_master_password) }}' \
      -m <<EOF
      ALTER SYSTEM STOP DATABASE {{ sap_hana_install_sid }};
      DROP DATABASE {{ sap_hana_install_sid }};
      CREATE DATABASE {{ sap_hana_install_sid }} ADD 'xsengine' SYSTEM USER PASSWORD {{ sap_hana_install_db_system_password|d(sap_hana_install_master_password) }};
      SELECT DATABASE_NAME, SERVICE_NAME, PORT, SQL_PORT, (PORT + 2) HTTP_PORT FROM SYS_DATABASES.M_SERVICES;
      EOF
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_install_sid | lower }}adm"
  when: not ansible_check_mode
  changed_when: no
  register: __sap_hana_install_register_recreate_tenant_database

- name: SAP HANA Post Install - Display the result of the hdbsql command
  ansible.builtin.debug:
    var: __sap_hana_install_register_recreate_tenant_database.stdout_lines
