---

- name: SAP HANA Post Install - Deduplicate values from /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    create: false
    regexp: (?i)^\s*{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}\s+
    state: absent

- name: SAP HANA Post Install - Update /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }} {{ ansible_fqdn }} {{ ansible_hostname }}"
