---

# Important variables

qe_sap_storage_cloud_type: 'generic'
# generic | az | aws

qe_sap_storage_action: 'prepare'
# prepare | remove


# Azure variables

qe_sap_storage_az_imds_json:
qe_sap_storage_az_imds_url: 'http://169.254.169.254/metadata/instance/compute?api-version=2020-09-01'
qe_sap_storage_az_vmsize_url: 'http://169.254.169.254/metadata/instance/compute/vmSize?api-version=2017-08-01&format=text'

qe_sap_storage_az_vmsize:

qe_sap_storage_az_lun: '/dev/disk/azure/scsi1/lun'
