---

################
# Azure Specific Pre-Tasks
################

# Create json format of IMDS
# Todo: Ansibilize this
- name: SAP Storage Preparation - {{ sap_storage_cloud_type | upper }} - Create json format of IMDS
  ansible.builtin.shell: |
    curl -H Metadata:true --noproxy "*" "{{ sap_storage_az_imds_url }}" | python3 -mjson.tool
  register: az_imds_reg
  args:
     executable: /bin/bash
# If this fails, that means this VM is not Azure?

- ansible.builtin.set_fact:
     sap_storage_az_imds_json: "{{ az_imds_reg.stdout }}"

# Pull VMSize
# Todo: Ansibilize this
- name: SAP Storage Preparation - {{ sap_storage_cloud_type | upper }} - Pull VMSize
  ansible.builtin.shell: |
    curl -H Metadata:true --noproxy "*" "{{ sap_storage_az_vmsize_url }}"
  register: az_vmsize_reg
  args:
     executable: /bin/bash

- ansible.builtin.debug:
     msg:
        - "{{ az_vmsize_reg.stdout }}"

- ansible.builtin.set_fact:
     sap_storage_az_vmsize: "{{ az_vmsize_reg.stdout }}"

# Include vars depending on VM Size
- name: SAP Storage Preparation - {{ sap_storage_cloud_type | upper }} - Load Variables for {{ sap_storage_az_vmsize }}
  ansible.builtin.include_vars: "{{ sap_storage_cloud_type }}_tasks/vmsizes/{{ sap_storage_az_vmsize }}.yml"
