---
- name: "SAP HSR - Check System Replication Status"
  shell: |
    source /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_ha_install_hana_hsr_sid | upper }}/HDB{{ sap_ha_install_hana_hsr_instance_number }}/exe/hdbnsutil \
    -sr_state
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_ha_install_hana_hsr_sid | lower }}adm"
  register: __sap_ha_install_hana_hsr_srstate
  changed_when: false
  failed_when: false
  until: __sap_ha_install_hana_hsr_srstate.rc == 0
  retries: 3
  delay: 60

# assert that the previous task produced a meaningful result
# specifically, ensure that the result has an 'stdout' attribute
- name: "Assert stdout is defined for System Replication Status"
  assert:
    that:
      - __sap_ha_install_hana_hsr_srstate.stdout is defined
    fail_msg: "'stdout' is not defined in '__sap_ha_install_hana_hsr_srstate'. Check the previous task execution."
    success_msg: "'stdout' is defined in '__sap_ha_install_hana_hsr_srstate'."

# looping through cluster definition to run on defined primary
# and apply the respective 'site' value
- name: "SAP HSR - Enable HANA System Replication on primary node"
  shell: |
    source /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_ha_install_hana_hsr_sid | upper }}/HDB{{ sap_ha_install_hana_hsr_instance_number }}/exe/hdbnsutil \
    -sr_enable --name="{{ item.hana_site }}"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_ha_install_hana_hsr_sid | lower }}adm"
  register: enablesr
  changed_when: "'successfully enabled system as system replication source site' in enablesr.stdout"
  when:
    - ansible_hostname == item.node_name
    - item.node_role is defined and item.node_role == 'primary'
    - ansible_hostname not in __sap_ha_install_hana_hsr_srstate.stdout
  loop: "{{ sap_ha_install_hana_hsr_cluster_nodes }}"
  loop_control:
    label: "{{ item.node_name }}"

# looping through cluster definition to run on secondary node
# and apply the respective 'site' value
- name: "SAP HSR - Register secondary node to HANA System Replication"
  shell: |
    source /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_ha_install_hana_hsr_sid | upper }}/HDB{{ sap_ha_install_hana_hsr_instance_number }}/exe/hdbnsutil \
    -sr_register --name={{ item.hana_site }} \
    --remoteHost={{ __sap_ha_install_hana_hsr_primary_node }} --remoteInstance={{ sap_ha_install_hana_hsr_instance_number }} \
    --replicationMode={{ sap_ha_install_hana_hsr_rep_mode }} --operationMode={{ sap_ha_install_hana_hsr_oper_mode }} \
    --online
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_ha_install_hana_hsr_sid | lower }}adm"
  register: registersr
  when:
    - ansible_hostname == item.node_name
    - item.node_role is not defined or item.node_role == 'secondary'
    - ansible_hostname not in __sap_ha_install_hana_hsr_srstate.stdout
  loop: "{{ sap_ha_install_hana_hsr_cluster_nodes }}"
  loop_control:
    label: "{{ item.node_name }}"

- name: "SAP HSR - Start HANA instance on secondary"
  shell: |
    /usr/sap/{{ sap_ha_install_hana_hsr_sid | upper }}/HDB{{ sap_ha_install_hana_hsr_instance_number }}/exe/sapcontrol \
    -nr {{ sap_ha_install_hana_hsr_instance_number }} -function StartSystem
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_ha_install_hana_hsr_sid | lower }}adm"
  register: startinstance
  changed_when: "'StartSystem' in startinstance.stdout"
  when:
    - ansible_hostname != __sap_ha_install_hana_hsr_primary_node
    - ansible_hostname not in __sap_ha_install_hana_hsr_srstate.stdout
