---
- name: "SAP HSR - check log_mode"
  tags: hsr_logmode
  become: true
  become_user: "{{ sap_ha_install_hana_hsr_sid | lower }}adm"
  shell: |
    grep "log_mode" /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/global/hdb/custom/config/global.ini | grep normal
  register: sap_ha_install_hana_hsr_log_mode
  failed_when: false
  changed_when: false

- name: "SAP HSR - Set log_mode to normal"
  tags: hsr_logmode
  become: true
  become_user: "{{ sap_ha_install_hana_hsr_sid | lower }}adm"
  shell: |
    /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/exe/hdb/hdbsql \
    -U {{ sap_ha_install_hana_hsr_hdbuserstore_system_backup_user }} \
    -m <<EOF
    ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'SYSTEM') SET ('persistence', 'log_mode') = 'normal' WITH RECONFIGURE;
    ALTER SYSTEM ALTER CONFIGURATION('global.ini','HOST','{{ ansible_hostname }}') SET ('persistence','log_mode') = 'normal' WITH RECONFIGURE;
    EOF
  args:
    executable: /bin/bash
  ignore_errors: true
  when: sap_ha_install_hana_hsr_log_mode.rc != '0'
