---
- name: "SAP HSR - Run backup for SYSTEMDB"
  shell: |
    /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/exe/hdb/hdbsql \
    -U {{ sap_ha_install_hana_hsr_hdbuserstore_system_backup_user }} \
    -m <<EOF
    BACKUP DATA FOR SYSTEMDB USING FILE ('data_bck');
    EOF
  args:
    executable: /bin/bash

- name: "SAP HSR - Run backup in TENANTDB {{ sap_ha_install_hana_hsr_sid }}"
  shell: |
    /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/exe/hdb/hdbsql \
    -U {{ sap_ha_install_hana_hsr_hdbuserstore_system_backup_user }} \
    -m <<EOF
    BACKUP DATA FOR {{ sap_ha_install_hana_hsr_sid }} USING FILE ('data_bck');
    EOF
  args:
    executable: /bin/bash
  failed_when: false
