#!/bin/bash
YAMLLINT_CMD="yamllint"
if [[ -n "${GITHUB_ACTIONS}" ]]; then
  YAMLLINT_CMD="${YAMLLINT_CMD} -f github "
fi

find ansible/ -type f -iname "*.yml" -or -iname "*.yaml" -exec ${YAMLLINT_CMD} {} +
