---
- name: Get cluster status
  ansible.builtin.command:
    cmd: crm configure show
  register: crm_conf_hana_show
  changed_when: false
  when: is_primary

- name: Set hana crm facts
  ansible.builtin.set_fact:
    crm_maintenance_mode: "{{ (crm_conf_hana_show.stdout | regex_search('maintenance-mode=([a-z]*)', '\\1'))[0] | default('unknown') }}"
    stonith_timeout: "{{ crm_conf_hana_show.stdout | regex_search('stonith-timeout') }}"  # this should be variable!
    hana_resource: "{{ crm_conf_hana_show.stdout | regex_search('primitive rsc_SAPHanaCtl_') }}"
    hana_clone: "{{ crm_conf_hana_show.stdout | regex_search('ms ms(.)_SAPHanaCtl_') }}"
    hana_topology_resource: "{{ crm_conf_hana_show.stdout | regex_search('primitive rsc_SAPHanaTpg') }}"
    hana_topology_clone: "{{ crm_conf_hana_show.stdout | regex_search('clone cln_SAPHanaTpg') }}"
    hana_filesystem_resource: "{{ crm_conf_show.stdout | regex_search('primitive rsc_SAPHanaFil_') }}"
    hana_filesystem_clone: "{{ crm_conf_show.stdout | regex_search('primitive cln_SAPHanaFil_') }}"
    ip_resource: "{{ crm_conf_hana_show.stdout | regex_search('primitive rsc_ip_') }}"
    ip_nc: "{{ crm_conf_hana_show.stdout | regex_search('primitive rsc_socat_') }}"
    ip_grp: "{{ crm_conf_hana_show.stdout | regex_search('group g_ip_') }}"
    ip_colo: "{{ crm_conf_hana_show.stdout | regex_search('colocation col_saphana_ip_') }}"
    cluster_order: "{{ crm_conf_hana_show.stdout | regex_search('order ord_SAPHana_') }}"
  when: is_primary
  changed_when: false

- name: Ensure maintenance mode is active
  ansible.builtin.command:
    cmd: crm maintenance on
  when: crm_maintenance_mode is false or crm_maintenance_mode == 'unknown'

- name: Create HANA topology resource
  ansible.builtin.command:
    cmd: >-
      crm configure primitive
      rsc_SAPHanaTpg_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}
      ocf:suse:SAPHanaTopology
      operations
      $id="rsc_sap2_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}-operations"
      op monitor interval="10" timeout="600"
      op start interval="0" timeout="600"
      op stop interval="0" timeout="300"
      params SID="{{ sap_hana_install_sid }}"
      InstanceNumber="{{ sap_hana_install_instance_number }}"
  when:
    - hana_topology_resource | length == 0
    - is_primary

- name: Create HANA topology clone
  ansible.builtin.command:
    cmd: >-
      crm configure clone
      cln_SAPHanaTpg_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}
      rsc_SAPHanaTpg_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}
      meta
      clone-node-max="1"
      target-role="Started"
      interleave="true"
  when:
    - hana_topology_clone | length == 0
    - is_primary

- name: Create HANA resource
  ansible.builtin.command:
    cmd: >-
      crm configure primitive
      {{ rsc_saphanactl }}
      ocf:suse:SAPHana
      operations
      $id="rsc_sap_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}-operations"
      op start interval="0" timeout="3600"
      op stop interval="0" timeout="3600"
      op promote interval="0" timeout="3600"
      op monitor interval="60" role="Master" timeout="700"
      op monitor interval="61" role="Slave" timeout="700"
      params
      SID="{{ sap_hana_install_sid }}"
      InstanceNumber="{{ sap_hana_install_instance_number }}"
      PREFER_SITE_TAKEOVER="true"
      DUPLICATE_PRIMARY_TIMEOUT="7200"
      AUTOMATED_REGISTER="false"
  when:
    - hana_resource | length == 0
    - is_primary

- name: Create HANA resource clone
  ansible.builtin.command:
    cmd: >-
      crm configure ms
      {{ ms_saphanactl }}
      {{ rsc_saphanactl }}
      meta
      notify="true"
      clone-max="2"
      clone-node-max="1"
      target-role="Started"
      interleave="true"
  when:
    - hana_clone | length == 0
    - is_primary

- name: Create HANA Filesystem resource
  ansible.builtin.command:
    cmd: >-
      crm configure primitive
      rsc_SAPHanaFil_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}
      ocf:suse:SAPHanaFilesystem
      operations
      $id="rsc_sap3_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}-operations"
      op start interval="0" timeout="10"
      op stop interval="0" timeout="20"
      op monitor interval="120" timeout="120"
      params
      SID="{{ sap_hana_install_sid }}"
      InstanceNumber="{{ sap_hana_install_instance_number }}"
      ON_FAIL_ACTION="fence"
  register: cmd_crm_chfr_output
  changed_when: cmd_crm_chfr_output.rc != 0
  when:
    - use_hana_sr_angi | bool
    - hana_filesystem_resource | length == 0

- name: Create HANA Filesystem clone
  ansible.builtin.command:
    cmd: >-
      crm configure clone
      cln_SAPHanaFil_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}
      rsc_SAPHanaFil_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}
      meta
      clone-max="2"
      clone-node-max="1"
      target-role="Started"
      interleave="true"
  register: cmd_crm_chfc_output
  changed_when: cmd_crm_chfc_output.rc != 0
  when:
    - use_hana_sr_angi | bool
    - hana_filesytem_clone | length == 0

- name: Configure colocation
  ansible.builtin.command:
    cmd: >-
      crm configure colocation
      col_saphana_ip_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}
      2000:
      rsc_ip_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}:Started
      {{ ms_saphanactl }}
  when: ip_colo | length == 0

- name: Configure order
  ansible.builtin.command:
    cmd: >-
      crm configure order
      ord_SAPHana
      Optional:
      cln_SAPHanaTpg_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}
      {{ ms_saphanactl }}
  when: cluster_order | length == 0

# Get current maintenance state
- name: Refresh cluster status
  ansible.builtin.command:
    cmd: crm configure show
  register: refreshed_crm_conf_show
  changed_when: false

- name: Refresh crm facts
  ansible.builtin.set_fact:
    refreshed_crm_maintenance_mode: "{{ (refreshed_crm_conf_show.stdout | regex_search('maintenance-mode=([a-z]*)', '\\1'))[0] | default('unknown') }}"
  changed_when: false

- name: Ensure maintenance mode is disabled
  ansible.builtin.command:
    cmd: crm maintenance off
  when: refreshed_crm_maintenance_mode is true or refreshed_crm_maintenance_mode == 'unknown'

# For debug purpose only
- name: Get cluster status at the end
  ansible.builtin.command:
    cmd: crm configure show
  changed_when: false
