name: Ansible
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Install all requirements
        run: |
          python3 -m pip install --upgrade -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Run ansible-yaml-lint
        run: |
           make static-ansible-yaml

      - name: Run ansible-playbooks syntax-check
        run: |
           make static-ansible-syntax
