name: Ansible

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - 'ansible/**'
      - 'requirements.txt'
      - '.github/workflows/ansible.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Install all requirements
        run: |
          python3 -m pip install --upgrade -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Run ansible static tests
        run: |
           make -n static-ansible
           make SHELL='sh -x' static-ansible
