name: Glue Script

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - 'scripts/qesap/**'
      - '.github/workflows/gluescript.yml'

env:
  TF_VERSION: 1.5.7

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # all available versions are in https://raw.githubusercontent.com/actions/python-versions/refs/heads/main/versions-manifest.json
        python-version: ['3.10.18', '3.11.13', '3.12.11', '3.13.8']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions

    - name: PyLint with tox
      working-directory: scripts/qesap/
      run: tox -e pylint
      env:
        PLATFORM: ${{ matrix.platform }}

    - name: flake8 with tox
      working-directory: scripts/qesap/
      run: tox -e flake8
      env:
        PLATFORM: ${{ matrix.platform }}

    - name: flake8 test code with tox
      working-directory: scripts/qesap/
      run: |
        tox -e flake8_test
      env:
        PLATFORM: ${{ matrix.platform }}

    - name: UT tox
      working-directory: scripts/qesap/
      run: tox
      env:
        PLATFORM: ${{ matrix.platform }}

    - name: Test UT variants
      working-directory: scripts/qesap/
      run: |
        tox -e pytest_verbose
        tox -e pytest_hypo
        tox -e pytest_finddep
      env:
        PLATFORM: '3.11.13'

    # Install the specific version of Terraform that the project support and
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_wrapper: false

    - name: Test e2e
      run: |
        python -m pip install -r requirements.txt
        ansible-galaxy install -r requirements.yml
        make test-e2e
