name: Glue Script

on:
  push:
    paths:
      - scripts/qesap/**
      - .github/workflows/gluescript.yml
  pull_request:
    paths:
      - scripts/qesap/**
      - .github/workflows/gluescript.yml

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-20.04]
        # all available versions are in https://github.com/actions/python-versions/blob/main/versions-manifest.json
        python-version: ['3.8.16', '3.9.15', '3.10.10', '3.11.5']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: PyLint with tox
      working-directory: scripts/qesap/
      run: tox -e pylint
      env:
        PLATFORM: ${{ matrix.platform }}
    - name: flake8 with tox
      working-directory: scripts/qesap/
      run: tox -e flake8
      env:
        PLATFORM: ${{ matrix.platform }}
    - name: Test with tox
      working-directory: scripts/qesap/
      run: tox
      env:
        PLATFORM: ${{ matrix.platform }}
