name: Tools environment
# Purpose of this workflow is to check that all binary the project
# is recommending are installable and usable on openSUSE TW.
# This workflow refer to th eDockerfile in the root of the repo.
on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - 'Dockerfile'
      - 'Dockerfile.leap'
      - 'requirements.txt'
      - 'requirements.yml'
      - '.github/workflows/tools.yml'
      - 'terraform/azure/version.tf'
      - 'terraform/aws/version.tf'
      - 'terraform/gcp/version.tf'
env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opensuse-version: ['Dockerfile', 'Dockerfile.leap']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.opensuse-version }} image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ matrix.opensuse-version }}

      - name: Test
        run: |
          cre=docker ./tools/image_test.sh ${{ github.run_id }}
