name: Tools environment

on:
  push:
    branches:
      - "main"
    paths:
      - Dockerfile
      - requirements.txt
      - requirements.yml
      - .github/workflows/tools.yml
  pull_request:
    paths:
      - Dockerfile
      - requirements.txt
      - requirements.yml
      - .github/workflows/tools.yml

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test
        run: |
          cre=docker ./tools/image_test.sh ${{ github.run_id }}
